version: '3'
services:
  db:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network
volumes:
  db:
    driver: local
networks:
  app-network: